# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"

# success_symbol = "[∞](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
# [time]
# success_symbol = "[ ⚡](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
# disabled = false
success_symbol = "[ ☀ ](bold green)"
error_symbol = "[ ☀ ](bold red)"
vimcmd_symbol = "[ ☽ ](bold green)"
vimcmd_visual_symbol = "[ ☽ ](bold yellow)"
